
default: &default
  adapter: postgresql
  encoding: unicode
  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: blogexam_development

  
test:
  <<: *default
  database: blogexam_test


production:
  <<: *default
  database: blogexam_production
  username: blogexam
  password: <%= ENV['BLOGEXAM_DATABASE_PASSWORD'] %>
